### ISSUE TITLE
大佬可以考虑在下个版本把luci-app-cifs-mount编译进去吗？可以在op上smb挂载nas的硬盘，还是挺有用的

### ISSUE THREAD

**Issue by sqh-world** [pmkol/openwrt-lite#1]
本人新手，已尝试在https://downloads.immortalwrt.org/releases/packages-23.05/x86_64/luci/
找到了这个插件手动安装，不知为何没有出现在页面上

**Comment by pmkol** [comment]
它已经被添加到了自定义编译选项中，你可以自编译固件 https://github.com/pmkol/openwrt-lite/commit/a3cd8c1ae72a7f32362dede0c777b302a78286de

另外这个插件已经添加到了扩展源中，你可以直接在软件包界面安装它

**Comment by sqh-world** [comment]
> 它已经被添加到了自定义编译选项中，你可以自编译固件 https://github.com/pmkol/openwrt-lite/commit/a3cd8c1ae72a7f32362dede0c777b302a78286de
> 
> 
> 
> 另外这个插件已经添加到了扩展源中，你可以直接在软件包界面安装它

谢谢大佬😎！我已搜索到并安装成功。请问是刚刚添加到源中的吗？我昨天搜索那时间还没有。。

**Comment by pmkol** [comment]
> > 它已经被添加到了自定义编译选项中，你可以自编译固件 [a3cd8c1](https://github.com/pmkol/openwrt-lite/commit/a3cd8c1ae72a7f32362dede0c777b302a78286de)
> > 另外这个插件已经添加到了扩展源中，你可以直接在软件包界面安装它
> 
> 谢谢大佬😎！我已搜索到并安装成功。请问是刚刚添加到源中的吗？我昨天搜索那时间还没有。。

是的，刚刚添加的
