### ISSUE TITLE
有几个插件麻烦大佬考虑考虑是否加入，谢谢

### ISSUE THREAD

**Issue by WoChen5770** [pmkol/openwrt-lite#3]
luci-app-turboacc
luci-theme-design
luci-app-homebox
luci-app-wrtbwmon

**Comment by pmkol** [comment]
这些都是LEDE的插件，与当前版本不兼容
luci-app-turboacc 固件默认已在内核级开启类似优化
luci-theme-design 主题不兼容当前系统
luci-app-homebox 已由 luci-app-speedtest 替代
luci-app-wrtbwmon 已由 _luci-app-nlbwmon 替代

**Comment by WoChen5770** [comment]
好的，感谢回复。
不过后两个试了一下不好用，好像luci-app-nlbwmon不能实时看网速

**Comment by WoChen5770** [comment]
不过开了sfe，流量不准的，流量统计也没用了，
